/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author flore
 */
public class ViewInicio extends javax.swing.JPanel {

    /**
     * Creates new form ViewInicio
     */
    public ViewInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_inicio_logo = new javax.swing.JPanel();
        jPanelAdminDeUSers1 = new javax.swing.JPanel();
        jPanelAdminDeUSers2 = new javax.swing.JPanel();
        jlNombre1 = new javax.swing.JLabel();

        jp_inicio_logo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 51, 0))); // NOI18N
        jp_inicio_logo.setOpaque(false);

        jPanelAdminDeUSers1.setBackground(new java.awt.Color(204, 51, 0));
        jPanelAdminDeUSers1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelAdminDeUSers1.setPreferredSize(new java.awt.Dimension(425, 60));

        jPanelAdminDeUSers2.setBackground(new java.awt.Color(0, 153, 204));
        jPanelAdminDeUSers2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelAdminDeUSers2.setPreferredSize(new java.awt.Dimension(425, 60));

        jlNombre1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jlNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jlNombre1.setText("S E D I T E K");

        javax.swing.GroupLayout jPanelAdminDeUSers2Layout = new javax.swing.GroupLayout(jPanelAdminDeUSers2);
        jPanelAdminDeUSers2.setLayout(jPanelAdminDeUSers2Layout);
        jPanelAdminDeUSers2Layout.setHorizontalGroup(
            jPanelAdminDeUSers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminDeUSers2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlNombre1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAdminDeUSers2Layout.setVerticalGroup(
            jPanelAdminDeUSers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminDeUSers2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelAdminDeUSers1Layout = new javax.swing.GroupLayout(jPanelAdminDeUSers1);
        jPanelAdminDeUSers1.setLayout(jPanelAdminDeUSers1Layout);
        jPanelAdminDeUSers1Layout.setHorizontalGroup(
            jPanelAdminDeUSers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
            .addGroup(jPanelAdminDeUSers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAdminDeUSers1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAdminDeUSers2, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelAdminDeUSers1Layout.setVerticalGroup(
            jPanelAdminDeUSers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
            .addGroup(jPanelAdminDeUSers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAdminDeUSers1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAdminDeUSers2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jp_inicio_logoLayout = new javax.swing.GroupLayout(jp_inicio_logo);
        jp_inicio_logo.setLayout(jp_inicio_logoLayout);
        jp_inicio_logoLayout.setHorizontalGroup(
            jp_inicio_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
            .addGroup(jp_inicio_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_inicio_logoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAdminDeUSers1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jp_inicio_logoLayout.setVerticalGroup(
            jp_inicio_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
            .addGroup(jp_inicio_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_inicio_logoLayout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(jPanelAdminDeUSers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp_inicio_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp_inicio_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelAdminDeUSers1;
    private javax.swing.JPanel jPanelAdminDeUSers2;
    private javax.swing.JLabel jlNombre1;
    private javax.swing.JPanel jp_inicio_logo;
    // End of variables declaration//GEN-END:variables
}
